[package]
name = "newtext"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2"
clap = { version = "4.5", features = ["derive"] }
regex = "1"

[[bin]]
name = "newtext"
path = "src/main.rs"
